name: FlipperDevicesInc.qFlipper PR
# based off of https://github.com/nushell/nushell/blob/main/.github/workflows/winget-submission.yml

on:
    workflow_dispatch:
    schedule:
        - cron: 3 0/4 * * *

jobs:
  winget:
    name: Publish FlipperDevicesInc.qFlipper winget package
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Utesgui
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install wingetcreate
      #   run: winget install wingetcreate --disable-interactivity --accept-source-agreements
      - name: Submit FlipperDevicesInc.qFlipper package
        working-directory: Utesgui
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
          WINGET_PKGS_FORK_REPO: ${{ vars.WINGET_PKGS_FORK_REPO }}
        run: .\scripts\Update-QFlipper.ps1

