name: GH Release based Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 0/4 * * *' # every 4 hours

jobs:
  update-releasebased:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Test' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: "Yubico.Authenticator"
            repo: "Yubico/yubioath-flutter"
            url: "https://github.com/Yubico/yubioath-flutter/releases/download/{VERSION}/yubico-authenticator-{VERSION}-win64.msi"
#          - id: "Yubico.YubikeyManager"
#            repo: "Yubico/yubikey-manager-qt"
#            url: "https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-{VERSION}-win32.exe"
          - id: "Yubico.YubiKeyManagerCLI"
            repo: "Yubico/yubikey-manager"
            url: "https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-{VERSION}-win64.msi"
          - id: "Anki.Anki"
            repo: "ankitects/anki"
            url: "https://github.com/ankitects/anki/releases/download/{VERSION}/anki-{VERSION}-windows-qt6.exe"
          - id: "EdgeTX.Companion"
            repo: "EdgeTX/edgetx"
            url: "https://github.com/EdgeTX/edgetx/releases/download/v{VERSION}/edgetx-cpn-win64-v{VERSION}.zip"
          - id: "Betaflight.Betaflight-Configurator"
            repo: "betaflight/betaflight-configurator"
            url: "https://github.com/betaflight/betaflight-configurator/releases/download/{VERSION}/betaflight-configurator_{VERSION}_win64-installer.exe"
          - id: "h3poteto.fedistar"
            repo: "h3poteto/fedistar"
            url: "https://github.com/h3poteto/fedistar/releases/download/v{VERSION}/fedistar_{VERSION}_x64_en-US.msi"
          - id: "hoppscotch.Hoppscotch"
            repo: "hoppscotch/releases"
            url: "https://github.com/hoppscotch/releases/releases/download/v{VERSION}/Hoppscotch_win_x64.msi"
          - id: "AdGuard.dnsproxy"
            repo: "AdguardTeam/dnsproxy"
            url: "https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-386-v{VERSION}.zip https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-amd64-v{VERSION}.zip https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-arm64-v{VERSION}.zip"
          - id: "OpenTofu.Tofu"
            repo: "opentofu/opentofu"
            url: "https://github.com/opentofu/opentofu/releases/download/v{VERSION}/tofu_{VERSION}_windows_386.zip https://github.com/opentofu/opentofu/releases/download/v{VERSION}/tofu_{VERSION}_windows_amd64.zip"
          - id: "mitmproxy.mitmproxy"
            repo: "mitmproxy/mitmproxy"
            url: "https://downloads.mitmproxy.org/{VERSION}/mitmproxy-{VERSION}-windows-x86_64-installer.exe"
          - id: "commercialhaskell.stack"
            repo: "commercialhaskell/stack"
            url: "https://github.com/commercialhaskell/stack/releases/download/v{VERSION}/stack-{VERSION}-windows-x86_64-installer.exe"
          - id: "JohnMacFarlane.Pandoc"
            repo: "jgm/pandoc"
            url: "https://github.com/jgm/pandoc/releases/download/{VERSION}/pandoc-{VERSION}-windows-x86_64.msi"
          - id: "RustDesk.RustDesk"
            repo: "rustdesk/rustdesk"
            url: "https://github.com/rustdesk/rustdesk/releases/download/{VERSION}/rustdesk-{VERSION}-x86-sciter.exe https://github.com/rustdesk/rustdesk/releases/download/{VERSION}/rustdesk-{VERSION}-x86_64.exe"
    steps:
    - name: Update Packages
      uses: b0t-at/winget-updater@b0t-main
      with:
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}
        komac-token: ${{ secrets.WINGET_PAT }}
        komac-version: latest
        custom-fork-owner: damn-good-b0t
        submit: ${{ vars.SUBMIT_PR }}
