name: Update StrawberryPerl.StrawberryPerl

on:
    workflow_dispatch:
    schedule:
        - cron: 3 0/4 * * *
env:
    PackageName: "StrawberryPerl.StrawberryPerl"
    Repo: "StrawberryPerl/Perl-Dist-Strawberry"

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Komac
        run: winget install --id RussellBanks.Komac --accept-package-agreements
      - name: Update package
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
          WINGET_PKGS_FORK_REPO: ${{ vars.WINGET_PKGS_FORK_REPO }}
        run: .\Scripts\Update-${{ env.PackageName }}.ps1